#!/usr/bin/env bash

set -e

# Start timer.
T="$(date +%s%N)"

echo 'Installing NodeKit…'
echo ''

# Ensure npm dependencies are up to date.
npm install

# Create distribution build.
./build

# Remove existing app folder if it exists.
rm -rf "${HOME}/.small-tech.org/nodekit/app"

# Ensure NodeKit folder exists that we are going to install into.
mkdir -p "${HOME}/.small-tech.org/nodekit"

# Copy distribution folder to installation location.
cp -R dist "${HOME}/.small-tech.org/nodekit/app"

# Remove old symlink if it exists.
sudo rm -f /usr/local/bin/nodekit

# Create the symlink to the NodeKit binary.
sudo ln -s "${HOME}/.small-tech.org/nodekit/app/nodekit" /usr/local/bin/nodekit

# Timing code courtesy of https://stackoverflow.com/a/3684051/92548
T="$(($(date +%s%N)-T))"
S="$((T/1000000000))"
M="$((T%1000000000/1000000))"

printf "\nInstalled in %ds %03dms!\n\n" "$((S%60))" "${M}"

echo 'Run using: nodekit <path to serve>'
