#!/usr/bin/env bash

set -e

# Save the base path so we can pass it to NodeKit so it can calculate the
# absolute path of the path to serve even if a relative path is given from
# the current working directory.
basePath=`pwd`

# Run NodeKit from NodeKit distribution folder not folder nodekit command
# was run from.
pushd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")" > /dev/null

until (QUIET=true NODE_OPTIONS='--require=./suppress-experimental.cjs' node --experimental-modules --experimental-specifier-resolution=node --experimental-loader ./loader-bundle.js ./nodekit-bundle.js --base-path="${basePath}" "$@"); do
  echo 'Restarting…'
  sleep 1
done

# Return to folder nodekit was evoked from when execution ends.
trap popd EXIT
