#!/usr/bin/env bash

set -e

# Run NodeKit from NodeKit distribution folder not folder nodekit command
# was run from.
pushd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"

NODE_OPTIONS='--require=./suppress-experimental.cjs' node --experimental-modules --experimental-specifier-resolution=node --experimental-loader ./loader-bundle.js ./nodekit-bundle.js "$@"

# Return to folder nodekit was evoked from when execution ends.
trap popd EXIT
